from utils import get_static_chapter

sample_timeline = [
    {
        "id": 0,
        "seek": 0,
        "start": 0.0,
        "end": 5.24,
        "text": " بسم الله الرحمن الرحيم",
        "tokens": [
            50365,
            4724,
            38251,
            21984,
            34892,
            5016,
            27842,
            34892,
            5016,
            32640,
            50646,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.059613170294926084,
        "compression_ratio": 1.8526315789473684,
        "no_speech_prob": 0.12210839241743088,
        "words": [
            {
                "word": " بسم",
                "start": 0.0,
                "end": 0.62,
                "probability": 0.999037116765976,
            },
            {
                "word": " الله",
                "start": 0.62,
                "end": 1.22,
                "probability": 0.9998748302459717,
            },
            {
                "word": " الرحمن",
                "start": 1.22,
                "end": 3.12,
                "probability": 0.9997772574424744,
            },
            {
                "word": " الرحيم",
                "start": 3.12,
                "end": 5.24,
                "probability": 0.9999051690101624,
            },
        ],
    },
    {
        "id": 1,
        "seek": 0,
        "start": 5.24,
        "end": 10.9,
        "text": " الحمد لله رب العالمين",
        "tokens": [
            50646,
            21542,
            2304,
            3215,
            24976,
            3224,
            12602,
            3555,
            18863,
            45340,
            9957,
            50920,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.059613170294926084,
        "compression_ratio": 1.8526315789473684,
        "no_speech_prob": 0.12210839241743088,
        "words": [
            {
                "word": " الحمد",
                "start": 5.24,
                "end": 7.22,
                "probability": 0.9991235931714376,
            },
            {
                "word": " لله",
                "start": 7.22,
                "end": 7.94,
                "probability": 0.9999478459358215,
            },
            {
                "word": " رب",
                "start": 7.94,
                "end": 8.64,
                "probability": 0.9998935163021088,
            },
            {
                "word": " العالمين",
                "start": 8.64,
                "end": 10.9,
                "probability": 0.9999727010726929,
            },
        ],
    },
    {
        "id": 2,
        "seek": 0,
        "start": 10.9,
        "end": 15.04,
        "text": " الرحمن الرحيم",
        "tokens": [50920, 34892, 5016, 27842, 34892, 5016, 32640, 51134],
        "temperature": 0.0,
        "avg_logprob": -0.059613170294926084,
        "compression_ratio": 1.8526315789473684,
        "no_speech_prob": 0.12210839241743088,
        "words": [
            {
                "word": " الرحمن",
                "start": 10.9,
                "end": 12.76,
                "probability": 0.9993590712547302,
            },
            {
                "word": " الرحيم",
                "start": 12.76,
                "end": 15.04,
                "probability": 0.999925454457601,
            },
        ],
    },
    {
        "id": 3,
        "seek": 0,
        "start": 15.04,
        "end": 19.5,
        "text": " مالك يوم الدين",
        "tokens": [51134, 3714, 6027, 4117, 7251, 20498, 32748, 9957, 51345],
        "temperature": 0.0,
        "avg_logprob": -0.059613170294926084,
        "compression_ratio": 1.8526315789473684,
        "no_speech_prob": 0.12210839241743088,
        "words": [
            {
                "word": " مالك",
                "start": 15.04,
                "end": 16.74,
                "probability": 0.9991008838017782,
            },
            {
                "word": " يوم",
                "start": 16.74,
                "end": 17.46,
                "probability": 0.9998584687709808,
            },
            {
                "word": " الدين",
                "start": 17.46,
                "end": 19.5,
                "probability": 0.9994561076164246,
            },
        ],
    },
    {
        "id": 4,
        "seek": 0,
        "start": 19.5,
        "end": 26.74,
        "text": " إياك نعبد وإياك نستعين",
        "tokens": [
            51345,
            11933,
            25528,
            4117,
            8717,
            3615,
            44510,
            4032,
            28814,
            25528,
            4117,
            8717,
            14851,
            3615,
            9957,
            51726,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.059613170294926084,
        "compression_ratio": 1.8526315789473684,
        "no_speech_prob": 0.12210839241743088,
        "words": [
            {
                "word": " إياك",
                "start": 19.5,
                "end": 22.34,
                "probability": 0.9988051652908325,
            },
            {
                "word": " نعبد",
                "start": 22.34,
                "end": 23.36,
                "probability": 0.999849538008372,
            },
            {
                "word": " وإياك",
                "start": 23.36,
                "end": 24.82,
                "probability": 0.9992002695798874,
            },
            {
                "word": " نستعين",
                "start": 24.82,
                "end": 26.74,
                "probability": 0.9998338520526886,
            },
        ],
    },
    {
        "id": 5,
        "seek": 2674,
        "start": 26.74,
        "end": 32.08,
        "text": " إهدنا الصراط المستقيم",
        "tokens": [
            50365,
            11933,
            3224,
            3215,
            8315,
            31767,
            2288,
            41193,
            9673,
            14851,
            4587,
            32640,
            50663,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.06524543645905286,
        "compression_ratio": 1.4574468085106382,
        "no_speech_prob": 0.0004552122263703495,
        "words": [
            {
                "word": " إهدنا",
                "start": 26.74,
                "end": 28.62,
                "probability": 0.8625649735331535,
            },
            {
                "word": " الصراط",
                "start": 28.62,
                "end": 29.66,
                "probability": 0.999579111735026,
            },
            {
                "word": " المستقيم",
                "start": 29.66,
                "end": 32.08,
                "probability": 0.9996929466724396,
            },
        ],
    },
    {
        "id": 6,
        "seek": 2674,
        "start": 32.699999999999996,
        "end": 37.78,
        "text": " صراط الذين أنعمت عليهم",
        "tokens": [
            50663,
            20328,
            2288,
            41193,
            32545,
            9957,
            14739,
            25957,
            2655,
            25894,
            16095,
            50934,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.06524543645905286,
        "compression_ratio": 1.4574468085106382,
        "no_speech_prob": 0.0004552122263703495,
        "words": [
            {
                "word": " صراط",
                "start": 32.589999999999996,
                "end": 34.26,
                "probability": 0.9988316694895426,
            },
            {
                "word": " الذين",
                "start": 34.26,
                "end": 35.38,
                "probability": 0.9998544752597809,
            },
            {
                "word": " أنعمت",
                "start": 35.38,
                "end": 36.56,
                "probability": 0.9994712869326273,
            },
            {
                "word": " عليهم",
                "start": 36.56,
                "end": 37.78,
                "probability": 0.999895304441452,
            },
        ],
    },
    {
        "id": 7,
        "seek": 2674,
        "start": 37.78,
        "end": 50.5,
        "text": " غير المغضوب عليهم ولا الضالين",
        "tokens": [
            50934,
            32771,
            13546,
            9673,
            17082,
            11242,
            37746,
            25894,
            16095,
            49429,
            6024,
            114,
            6027,
            9957,
            51618,
        ],
        "temperature": 0.0,
        "avg_logprob": -0.06524543645905286,
        "compression_ratio": 1.4574468085106382,
        "no_speech_prob": 0.0004552122263703495,
        "words": [
            {
                "word": " غير",
                "start": 37.78,
                "end": 39.42,
                "probability": 0.9951275587081909,
            },
            {
                "word": " المغضوب",
                "start": 39.42,
                "end": 41.36,
                "probability": 0.9993110150098801,
            },
            {
                "word": " عليهم",
                "start": 41.36,
                "end": 43.06,
                "probability": 0.9999457597732544,
            },
            {
                "word": " ولا",
                "start": 43.06,
                "end": 44.04,
                "probability": 0.9820982813835144,
            },
            {
                "word": " الضالين",
                "start": 44.04,
                "end": 50.5,
                "probability": 0.9926542788743973,
            },
        ],
    },
]


sample_chapter = {
    "verses": [
        {
            "id": 1,
            "verse_number": 1,
            "verse_key": "1:1",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ",
            "chapter_id": 1,
            "text_imlaei_simple": "بسم الله الرحمن الرحيم",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 1,
                    "position": 1,
                    "audio_url": "wbw/001_001_001.mp3",
                    "verse_key": "1:1",
                    "verse_id": 1,
                    "location": "1:1:1",
                    "text_uthmani": "بِسْمِ",
                    "code_v2": "ﱁ",
                    "qpc_uthmani_hafs": "بِسۡمِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 9,
                    "text": "ﱁ",
                    "translation": {
                        "text": "In (the) name",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "bis'mi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 2,
                    "position": 2,
                    "audio_url": "wbw/001_001_002.mp3",
                    "verse_key": "1:1",
                    "verse_id": 1,
                    "location": "1:1:2",
                    "text_uthmani": "ٱللَّهِ",
                    "code_v2": "ﱂ",
                    "qpc_uthmani_hafs": "ٱللَّهِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 9,
                    "text": "ﱂ",
                    "translation": {
                        "text": "(of) Allah",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-lahi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 3,
                    "position": 3,
                    "audio_url": "wbw/001_001_003.mp3",
                    "verse_key": "1:1",
                    "verse_id": 1,
                    "location": "1:1:3",
                    "text_uthmani": "ٱلرَّحْمَـٰنِ",
                    "code_v2": "ﱃ",
                    "qpc_uthmani_hafs": "ٱلرَّحۡمَٰنِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 9,
                    "text": "ﱃ",
                    "translation": {
                        "text": "the Most Gracious",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-raḥmāni",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 4,
                    "position": 4,
                    "audio_url": "wbw/001_001_004.mp3",
                    "verse_key": "1:1",
                    "verse_id": 1,
                    "location": "1:1:4",
                    "text_uthmani": "ٱلرَّحِيمِ",
                    "code_v2": "ﱄ",
                    "qpc_uthmani_hafs": "ٱلرَّحِيمِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 9,
                    "text": "ﱄ",
                    "translation": {
                        "text": "the Most Merciful",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-raḥīmi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 5,
                    "position": 5,
                    "audio_url": None,
                    "verse_key": "1:1",
                    "verse_id": 1,
                    "location": "1:1:5",
                    "text_uthmani": "١",
                    "code_v2": "ﱅ",
                    "qpc_uthmani_hafs": "١",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 9,
                    "text": "ﱅ",
                    "translation": {
                        "text": "(1)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 0},
            "translations": [
                {
                    "id": 96343,
                    "resource_id": 20,
                    "text": "In the name of Allāh,<sup foot_note=195932>1</sup> the Entirely Merciful, the Especially Merciful.<sup foot_note=195931>2</sup>",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 2,
            "verse_number": 2,
            "verse_key": "1:2",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ",
            "chapter_id": 1,
            "text_imlaei_simple": "الحمد لله رب العالمين",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 1130,
                    "position": 1,
                    "audio_url": "wbw/001_002_001.mp3",
                    "verse_key": "1:2",
                    "verse_id": 2,
                    "location": "1:2:1",
                    "text_uthmani": "ٱلْحَمْدُ",
                    "code_v2": "ﱆ",
                    "qpc_uthmani_hafs": "ٱلۡحَمۡدُ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 10,
                    "text": "ﱆ",
                    "translation": {
                        "text": "All praises and thanks",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "al-ḥamdu",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 1131,
                    "position": 2,
                    "audio_url": "wbw/001_002_002.mp3",
                    "verse_key": "1:2",
                    "verse_id": 2,
                    "location": "1:2:2",
                    "text_uthmani": "لِلَّهِ",
                    "code_v2": "ﱇ",
                    "qpc_uthmani_hafs": "لِلَّهِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 10,
                    "text": "ﱇ",
                    "translation": {
                        "text": "(be) to Allah",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "lillahi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 1132,
                    "position": 3,
                    "audio_url": "wbw/001_002_003.mp3",
                    "verse_key": "1:2",
                    "verse_id": 2,
                    "location": "1:2:3",
                    "text_uthmani": "رَبِّ",
                    "code_v2": "ﱈ",
                    "qpc_uthmani_hafs": "رَبِّ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 10,
                    "text": "ﱈ",
                    "translation": {
                        "text": "the Lord",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "rabbi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 1133,
                    "position": 4,
                    "audio_url": "wbw/001_002_004.mp3",
                    "verse_key": "1:2",
                    "verse_id": 2,
                    "location": "1:2:4",
                    "text_uthmani": "ٱلْعَـٰلَمِينَ",
                    "code_v2": "ﱉ",
                    "qpc_uthmani_hafs": "ٱلۡعَٰلَمِينَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 10,
                    "text": "ﱉ",
                    "translation": {
                        "text": "of the universe",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-ʿālamīna",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 1134,
                    "position": 5,
                    "audio_url": None,
                    "verse_key": "1:2",
                    "verse_id": 2,
                    "location": "1:2:5",
                    "text_uthmani": "٢",
                    "code_v2": "ﱊ",
                    "qpc_uthmani_hafs": "٢",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 10,
                    "text": "ﱊ",
                    "translation": {
                        "text": "(2)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 6493},
            "translations": [
                {
                    "id": 96493,
                    "resource_id": 20,
                    "text": "[All] praise is [due] to Allāh, Lord<sup foot_note=195933>1</sup> of the worlds -",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 3,
            "verse_number": 3,
            "verse_key": "1:3",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ",
            "chapter_id": 1,
            "text_imlaei_simple": "الرحمن الرحيم",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 2953,
                    "position": 1,
                    "audio_url": "wbw/001_003_001.mp3",
                    "verse_key": "1:3",
                    "verse_id": 3,
                    "location": "1:3:1",
                    "text_uthmani": "ٱلرَّحْمَـٰنِ",
                    "code_v2": "ﱋ",
                    "qpc_uthmani_hafs": "ٱلرَّحۡمَٰنِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱋ",
                    "translation": {
                        "text": "The Most Gracious",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "al-raḥmāni",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 2954,
                    "position": 2,
                    "audio_url": "wbw/001_003_002.mp3",
                    "verse_key": "1:3",
                    "verse_id": 3,
                    "location": "1:3:2",
                    "text_uthmani": "ٱلرَّحِيمِ",
                    "code_v2": "ﱌ",
                    "qpc_uthmani_hafs": "ٱلرَّحِيمِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱌ",
                    "translation": {
                        "text": "the Most Merciful",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-raḥīmi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 2955,
                    "position": 3,
                    "audio_url": None,
                    "verse_key": "1:3",
                    "verse_id": 3,
                    "location": "1:3:3",
                    "text_uthmani": "٣",
                    "code_v2": "ﱍ",
                    "qpc_uthmani_hafs": "٣",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱍ",
                    "translation": {
                        "text": "(3)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 11546},
            "translations": [
                {
                    "id": 96606,
                    "resource_id": 20,
                    "text": "The Entirely Merciful, the Especially Merciful,",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 4,
            "verse_number": 4,
            "verse_key": "1:4",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "مَـٰلِكِ يَوْمِ ٱلدِّينِ",
            "chapter_id": 1,
            "text_imlaei_simple": "مالك يوم الدين",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 3252,
                    "position": 1,
                    "audio_url": "wbw/001_004_001.mp3",
                    "verse_key": "1:4",
                    "verse_id": 4,
                    "location": "1:4:1",
                    "text_uthmani": "مَـٰلِكِ",
                    "code_v2": "ﱎ",
                    "qpc_uthmani_hafs": "مَٰلِكِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱎ",
                    "translation": {
                        "text": "(The) Master",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "māliki",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 3253,
                    "position": 2,
                    "audio_url": "wbw/001_004_002.mp3",
                    "verse_key": "1:4",
                    "verse_id": 4,
                    "location": "1:4:2",
                    "text_uthmani": "يَوْمِ",
                    "code_v2": "ﱏ",
                    "qpc_uthmani_hafs": "يَوۡمِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱏ",
                    "translation": {
                        "text": "(of the) Day",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "yawmi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 3254,
                    "position": 3,
                    "audio_url": "wbw/001_004_003.mp3",
                    "verse_key": "1:4",
                    "verse_id": 4,
                    "location": "1:4:3",
                    "text_uthmani": "ٱلدِّينِ",
                    "code_v2": "ﱐ",
                    "qpc_uthmani_hafs": "ٱلدِّينِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱐ",
                    "translation": {
                        "text": "(of the) Judgment",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-dīni",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 3255,
                    "position": 4,
                    "audio_url": None,
                    "verse_key": "1:4",
                    "verse_id": 4,
                    "location": "1:4:4",
                    "text_uthmani": "٤",
                    "code_v2": "ﱑ",
                    "qpc_uthmani_hafs": "٤",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 11,
                    "text": "ﱑ",
                    "translation": {
                        "text": "(4)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 15985},
            "translations": [
                {
                    "id": 96653,
                    "resource_id": 20,
                    "text": "Sovereign of the Day of Recompense.<sup foot_note=195934>1</sup>",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 5,
            "verse_number": 5,
            "verse_key": "1:5",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
            "chapter_id": 1,
            "text_imlaei_simple": "اياك نعبد واياك نستعين",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 5334,
                    "position": 1,
                    "audio_url": "wbw/001_005_001.mp3",
                    "verse_key": "1:5",
                    "verse_id": 5,
                    "location": "1:5:1",
                    "text_uthmani": "إِيَّاكَ",
                    "code_v2": "ﱒ",
                    "qpc_uthmani_hafs": "إِيَّاكَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱒ",
                    "translation": {
                        "text": "You Alone",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "iyyāka",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 5335,
                    "position": 2,
                    "audio_url": "wbw/001_005_002.mp3",
                    "verse_key": "1:5",
                    "verse_id": 5,
                    "location": "1:5:2",
                    "text_uthmani": "نَعْبُدُ",
                    "code_v2": "ﱓ",
                    "qpc_uthmani_hafs": "نَعۡبُدُ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱓ",
                    "translation": {
                        "text": "we worship",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "naʿbudu",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 5336,
                    "position": 3,
                    "audio_url": "wbw/001_005_003.mp3",
                    "verse_key": "1:5",
                    "verse_id": 5,
                    "location": "1:5:3",
                    "text_uthmani": "وَإِيَّاكَ",
                    "code_v2": "ﱔ",
                    "qpc_uthmani_hafs": "وَإِيَّاكَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱔ",
                    "translation": {
                        "text": "and You Alone",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "wa-iyyāka",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 5337,
                    "position": 4,
                    "audio_url": "wbw/001_005_004.mp3",
                    "verse_key": "1:5",
                    "verse_id": 5,
                    "location": "1:5:4",
                    "text_uthmani": "نَسْتَعِينُ",
                    "code_v2": "ﱕ",
                    "qpc_uthmani_hafs": "نَسۡتَعِينُ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱕ",
                    "translation": {
                        "text": "we ask for help",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "nastaʿīnu",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 5338,
                    "position": 5,
                    "audio_url": None,
                    "verse_key": "1:5",
                    "verse_id": 5,
                    "location": "1:5:5",
                    "text_uthmani": "٥",
                    "code_v2": "ﱖ",
                    "qpc_uthmani_hafs": "٥",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱖ",
                    "translation": {
                        "text": "(5)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 21521},
            "translations": [
                {
                    "id": 96707,
                    "resource_id": 20,
                    "text": "It is You we worship and You we ask for help.",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 6,
            "verse_number": 6,
            "verse_key": "1:6",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
            "chapter_id": 1,
            "text_imlaei_simple": "اهدنا الصراط المستقيم",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 6844,
                    "position": 1,
                    "audio_url": "wbw/001_006_001.mp3",
                    "verse_key": "1:6",
                    "verse_id": 6,
                    "location": "1:6:1",
                    "text_uthmani": "ٱهْدِنَا",
                    "code_v2": "ﱗ",
                    "qpc_uthmani_hafs": "ٱهۡدِنَا",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 12,
                    "text": "ﱗ",
                    "translation": {
                        "text": "Guide us",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "ih'dinā",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 6845,
                    "position": 2,
                    "audio_url": "wbw/001_006_002.mp3",
                    "verse_key": "1:6",
                    "verse_id": 6,
                    "location": "1:6:2",
                    "text_uthmani": "ٱلصِّرَٰطَ",
                    "code_v2": "ﱘ",
                    "qpc_uthmani_hafs": "ٱلصِّرَٰطَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱘ",
                    "translation": {
                        "text": "(to) the path",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-ṣirāṭa",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 6846,
                    "position": 3,
                    "audio_url": "wbw/001_006_003.mp3",
                    "verse_key": "1:6",
                    "verse_id": 6,
                    "location": "1:6:3",
                    "text_uthmani": "ٱلْمُسْتَقِيمَ",
                    "code_v2": "ﱙ",
                    "qpc_uthmani_hafs": "ٱلۡمُسۡتَقِيمَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱙ",
                    "translation": {
                        "text": "the straight",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-mus'taqīma",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 6847,
                    "position": 4,
                    "audio_url": None,
                    "verse_key": "1:6",
                    "verse_id": 6,
                    "location": "1:6:4",
                    "text_uthmani": "٦",
                    "code_v2": "ﱚ",
                    "qpc_uthmani_hafs": "٦",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱚ",
                    "translation": {
                        "text": "(6)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 27835},
            "translations": [
                {
                    "id": 96503,
                    "resource_id": 20,
                    "text": "Guide us to the straight path -",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
        {
            "id": 7,
            "verse_number": 7,
            "verse_key": "1:7",
            "hizb_number": 1,
            "rub_el_hizb_number": 1,
            "ruku_number": 1,
            "manzil_number": 1,
            "sajdah_number": None,
            "text_uthmani": "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
            "chapter_id": 1,
            "text_imlaei_simple": "صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين",
            "page_number": 1,
            "juz_number": 1,
            "words": [
                {
                    "id": 8411,
                    "position": 1,
                    "audio_url": "wbw/001_007_001.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:1",
                    "text_uthmani": "صِرَٰطَ",
                    "code_v2": "ﱛ",
                    "qpc_uthmani_hafs": "صِرَٰطَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱛ",
                    "translation": {
                        "text": "(The) path",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "ṣirāṭa",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8412,
                    "position": 2,
                    "audio_url": "wbw/001_007_002.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:2",
                    "text_uthmani": "ٱلَّذِينَ",
                    "code_v2": "ﱜ",
                    "qpc_uthmani_hafs": "ٱلَّذِينَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱜ",
                    "translation": {
                        "text": "(of) those",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "alladhīna",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8413,
                    "position": 3,
                    "audio_url": "wbw/001_007_003.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:3",
                    "text_uthmani": "أَنْعَمْتَ",
                    "code_v2": "ﱝ",
                    "qpc_uthmani_hafs": "أَنۡعَمۡتَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 13,
                    "text": "ﱝ",
                    "translation": {
                        "text": "You have bestowed (Your) Favors",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "anʿamta",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8414,
                    "position": 4,
                    "audio_url": "wbw/001_007_004.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:4",
                    "text_uthmani": "عَلَيْهِمْ",
                    "code_v2": "ﱞ",
                    "qpc_uthmani_hafs": "عَلَيۡهِمۡ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 14,
                    "text": "ﱞ",
                    "translation": {
                        "text": "on them",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "ʿalayhim",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8415,
                    "position": 5,
                    "audio_url": "wbw/001_007_005.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:5",
                    "text_uthmani": "غَيْرِ",
                    "code_v2": "ﱟ",
                    "qpc_uthmani_hafs": "غَيۡرِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 14,
                    "text": "ﱟ",
                    "translation": {
                        "text": "not (of)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "ghayri",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8416,
                    "position": 6,
                    "audio_url": "wbw/001_007_006.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:6",
                    "text_uthmani": "ٱلْمَغْضُوبِ",
                    "code_v2": "ﱠ",
                    "qpc_uthmani_hafs": "ٱلۡمَغۡضُوبِ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 14,
                    "text": "ﱠ",
                    "translation": {
                        "text": "those who earned (Your) wrath",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-maghḍūbi",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8417,
                    "position": 7,
                    "audio_url": "wbw/001_007_007.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:7",
                    "text_uthmani": "عَلَيْهِمْ",
                    "code_v2": "ﱡ",
                    "qpc_uthmani_hafs": "عَلَيۡهِمۡ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 14,
                    "text": "ﱡ",
                    "translation": {
                        "text": "on themselves",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "ʿalayhim",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8418,
                    "position": 8,
                    "audio_url": "wbw/001_007_008.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:8",
                    "text_uthmani": "وَلَا",
                    "code_v2": "ﱢ",
                    "qpc_uthmani_hafs": "وَلَا",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 15,
                    "text": "ﱢ",
                    "translation": {
                        "text": "and not",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "walā",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8419,
                    "position": 9,
                    "audio_url": "wbw/001_007_009.mp3",
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:9",
                    "text_uthmani": "ٱلضَّآلِّينَ",
                    "code_v2": "ﱣ",
                    "qpc_uthmani_hafs": "ٱلضَّآلِّينَ",
                    "char_type_name": "word",
                    "page_number": 1,
                    "line_number": 15,
                    "text": "ﱣ",
                    "translation": {
                        "text": "(of) those who go astray",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": "l-ḍālīna",
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
                {
                    "id": 8420,
                    "position": 10,
                    "audio_url": None,
                    "verse_key": "1:7",
                    "verse_id": 7,
                    "location": "1:7:10",
                    "text_uthmani": "٧",
                    "code_v2": "ﱤ",
                    "qpc_uthmani_hafs": "٧",
                    "char_type_name": "end",
                    "page_number": 1,
                    "line_number": 15,
                    "text": "ﱤ",
                    "translation": {
                        "text": "(7)",
                        "language_name": "english",
                        "language_id": 38,
                    },
                    "transliteration": {
                        "text": None,
                        "language_name": "english",
                        "language_id": 38,
                    },
                },
            ],
            "timestamps": {"timestamp_from": 33388},
            "translations": [
                {
                    "id": 96932,
                    "resource_id": 20,
                    "text": "The path of those upon whom You have bestowed favor, not of those who have earned [Your] anger or of those who are astray.",
                    "resource_name": "Saheeh International",
                    "language_id": 38,
                }
            ],
        },
    ],
    "pagination": {
        "per_page": 7,
        "current_page": 1,
        "next_page": None,
        "total_pages": 1,
        "total_records": 7,
    },
}

sample_audio_file = {
    "audio_files": [
        {
            "id": 457,
            "chapter_id": 1,
            "file_size": 710784,
            "format": "mp3",
            "audio_url": "https://download.quranicaudio.com/qdc/abu_bakr_shatri/murattal/1.mp3",
            "duration": 53000,
            "verse_timings": [
                {
                    "verse_key": "1:1",
                    "timestamp_from": 0,
                    "timestamp_to": 6493,
                    "duration": -6493,
                    "segments": [
                        [1, 0, 630],
                        [2, 650, 1570],
                        [3, 1570, 3110],
                        [4, 3110, 5590],
                    ],
                },
                {
                    "verse_key": "1:2",
                    "timestamp_from": 6493,
                    "timestamp_to": 11546,
                    "duration": -5053,
                    "segments": [
                        [1, 6493, 7243],
                        [2, 7243, 8123],
                        [3, 8143, 8723],
                        [4, 8723, 11193],
                    ],
                },
                {
                    "verse_key": "1:3",
                    "timestamp_from": 11546,
                    "timestamp_to": 15985,
                    "duration": -4439,
                    "segments": [[1, 11546, 12806], [2, 12916, 15366]],
                },
                {
                    "verse_key": "1:4",
                    "timestamp_from": 15985,
                    "timestamp_to": 21521,
                    "duration": -5536,
                    "segments": [
                        [1, 15985, 16505],
                        [2, 16705, 17235],
                        [3, 17265, 19155],
                    ],
                },
                {
                    "verse_key": "1:5",
                    "timestamp_from": 21521,
                    "timestamp_to": 27835,
                    "duration": -6314,
                    "segments": [
                        [1, 21521, 22591],
                        [2, 22591, 23471],
                        [3, 23631, 25001],
                        [4, 25001, 27391],
                    ],
                },
                {
                    "verse_key": "1:6",
                    "timestamp_from": 27835,
                    "timestamp_to": 33388,
                    "duration": -5553,
                    "segments": [
                        [1, 27835, 28265],
                        [2, 28265, 29405],
                        [3, 29405, 32545],
                    ],
                },
                {
                    "verse_key": "1:7",
                    "timestamp_from": 33388,
                    "timestamp_to": 53092,
                    "duration": -19704,
                    "segments": [
                        [1, 33388, 34338],
                        [2, 34338, 35448],
                        [3, 35518, 36698],
                        [4, 36718, 38678],
                        [5, 38678, 39608],
                        [6, 39628, 41638],
                        [7, 41638, 43778],
                        [8, 43778, 44218],
                        [9, 44338, 51818],
                    ],
                },
            ],
        }
    ]
}


def get_chapter():
    return get_static_chapter(sample_chapter, sample_audio_file)
